apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: prom-pvc
  labels:
      name: prometheus
spec:  
  storageClassName: manual  
  accessModes:
   - ReadWriteOnce
  resources:
   requests:   
     storage: 1Gi
   

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: grafana-pvc
   labels:
     name: grafana
spec:
   storageClassName: manual
   accessModes:
    - ReadWriteOnce
   resources:
    requests:
      storage: 1Gi
